name: Deploy to testnet and verify on etherscan

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  deploy_and_verify:
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      DEPLOYMENT_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up NodeJS
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: run deployment script
      run: |
        npx hardhat run scripts/deploy.ts --network sapolia
    - name: Verify sourcecode on etherscan
      run: |
        npx hardhat verify $SC_ADDRESS --network sapolia
