name: deploy and verify smartcontract

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  deploy_and_verify:
    runs-on: ubuntu-latest

    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      ALCHEMY_PROVIDER_URL: ${{ secrets.ALCHEMY_PROVIDER_URL }}
      SMARTCONTRACT_ADMIN_PRIVATE_KEY: ${{ secrets.SMARTCONTRACT_ADMIN_PRIVATE_KEY }}
      UPDATE_ORG_VARIABLES_TOKEN: ${{ secrets.UPDATE_ORG_VARIABLES_TOKEN }}
      ARTIS_ORG_NAME: ${{ github.repository_owner }}
      ARTIS_SC_VARIABLE_NAME: "ARTIS_SC_ADDRESS"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: installing solc
        run: npm install -g solc

      - name: compile solidity
        run: npx hardhat compile

      - name: deploy contract
        run: npx hardhat run scripts/deploy.ts --network sepolia

      - name: waiting...
        run: sleep 60s

      - name: verify contract on etherscan
        run: npx hardhat verify $SC_ADDRESS --network sepolia
