name: deploy to testnet and verify sourcecode

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

  workflow_dispatch:

jobs:
  deploy_and_verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
        
      - name: setting env variables
        run: |
          export ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}
          export DEPLOYMENT_PRIVATE_KEY=${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
          export ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }} 

      - name: debugging
        run: echo $ETHERSCAN_API_KEY

      - name: Install dependencies
        run: npm ci

      - name: deploy contract
        run: npx hardhat run scripts/deploy.ts --network sapolia

      - name: verify contract on etherscan
        run: npx hardhat verify $SC_ADDRESS --network sapolia
