# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy to testnet and verify on etherscan

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  deploy_and_verify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up NodeJS
      uses: actions/setup-node@v2.5.2
    - name: Install dependencies
      run: npm ci
    - name: add environment variables
      run: |
        export ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}
        export DEPLOYMENT_PRIVATE_KEY=${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
        export ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}
    - name: run deployment script
      run: |
        npx hardhat run scripts/deploy.ts --network sapolia
    - name: Verify sourcecode on etherscan
      run: |
        npx hardhat verify $SC_ADDRESS --network sapolia
